//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS.Website1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LIMS.Website1.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acts/Regulations.
        /// </summary>
        public static string ActsRegulation {
            get {
                return ResourceManager.GetString("ActsRegulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisement.
        /// </summary>
        public static string Advertisement {
            get {
                return ResourceManager.GetString("Advertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Internal Affairs and Law.
        /// </summary>
        public static string Antarik {
            get {
                return ResourceManager.GetString("Antarik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Economic Affairs and Planning.
        /// </summary>
        public static string ArthikMamila {
            get {
                return ResourceManager.GetString("ArthikMamila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagamati Province.
        /// </summary>
        public static string Bagmati {
            get {
                return ResourceManager.GetString("Bagmati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banner.
        /// </summary>
        public static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Physical Infrastructure Development.
        /// </summary>
        public static string Bhautik {
            get {
                return ResourceManager.GetString("Bhautik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Land Management, Agriculture &amp; Cooperative.
        /// </summary>
        public static string Bhumi {
            get {
                return ResourceManager.GetString("Bhumi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Page Content.
        /// </summary>
        public static string ChangeContent {
            get {
                return ResourceManager.GetString("ChangeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organogram.
        /// </summary>
        public static string CommissionOrganogram {
            get {
                return ResourceManager.GetString("CommissionOrganogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        public static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail.
        /// </summary>
        public static string ContactDetail {
            get {
                return ResourceManager.GetString("ContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copywrite Reserved.
        /// </summary>
        public static string Copywrite {
            get {
                return ResourceManager.GetString("Copywrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curriculum.
        /// </summary>
        public static string Curriculum {
            get {
                return ResourceManager.GetString("Curriculum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dicisions.
        /// </summary>
        public static string Dicision {
            get {
                return ResourceManager.GetString("Dicision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directives/Procedure.
        /// </summary>
        public static string DirectivesProc {
            get {
                return ResourceManager.GetString("DirectivesProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E..
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Center.
        /// </summary>
        public static string ExamCenter {
            get {
                return ResourceManager.GetString("ExamCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federal Links.
        /// </summary>
        public static string Federal {
            get {
                return ResourceManager.GetString("Federal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string fHome {
            get {
                return ResourceManager.GetString("fHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FiscalYear.
        /// </summary>
        public static string fiscalYear {
            get {
                return ResourceManager.GetString("fiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms.
        /// </summary>
        public static string Forms {
            get {
                return ResourceManager.GetString("Forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string frontGallery {
            get {
                return ResourceManager.GetString("frontGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string Goals {
            get {
                return ResourceManager.GetString("Goals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hetauda, Makwanpur.
        /// </summary>
        public static string Hetauda {
            get {
                return ResourceManager.GetString("Hetauda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Links.
        /// </summary>
        public static string ImpLink {
            get {
                return ResourceManager.GetString("ImpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Link.
        /// </summary>
        public static string ImportantInfo {
            get {
                return ResourceManager.GetString("ImportantInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string InformationComm {
            get {
                return ResourceManager.GetString("InformationComm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        public static string Introductions {
            get {
                return ResourceManager.GetString("Introductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Updates.
        /// </summary>
        public static string latestUpdates {
            get {
                return ResourceManager.GetString("latestUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter/Circulars.
        /// </summary>
        public static string LetterCirulars {
            get {
                return ResourceManager.GetString("LetterCirulars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Level.
        /// </summary>
        public static string localLevel {
            get {
                return ResourceManager.GetString("localLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Coverage.
        /// </summary>
        public static string MediaCoverage {
            get {
                return ResourceManager.GetString("MediaCoverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Federal Affairs &amp; General Administration.
        /// </summary>
        public static string Moga {
            get {
                return ResourceManager.GetString("Moga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of Chief Minister and Council of Ministers.
        /// </summary>
        public static string MukhyaMantri {
            get {
                return ResourceManager.GetString("MukhyaMantri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted List.
        /// </summary>
        public static string NameList {
            get {
                return ResourceManager.GetString("NameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News/Event.
        /// </summary>
        public static string NewsEvent {
            get {
                return ResourceManager.GetString("NewsEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notices.
        /// </summary>
        public static string Notice {
            get {
                return ResourceManager.GetString("Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Public Service Commission, Bagmati Province.
        /// </summary>
        public static string officeName {
            get {
                return ResourceManager.GetString("officeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Officials.
        /// </summary>
        public static string Officials {
            get {
                return ResourceManager.GetString("Officials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interview.
        /// </summary>
        public static string OralExam {
            get {
                return ResourceManager.GetString("OralExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organogram.
        /// </summary>
        public static string Organogram {
            get {
                return ResourceManager.GetString("Organogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Police &amp; Other Organized Agencies.
        /// </summary>
        public static string otherOrganized {
            get {
                return ResourceManager.GetString("otherOrganized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Staffs.
        /// </summary>
        public static string OurStaffs {
            get {
                return ResourceManager.GetString("OurStaffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone: 057-590613,14,15.
        /// </summary>
        public static string Phone1 {
            get {
                return ResourceManager.GetString("Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 057-590614.
        /// </summary>
        public static string Phone2 {
            get {
                return ResourceManager.GetString("Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 057-590615.
        /// </summary>
        public static string Phone3 {
            get {
                return ResourceManager.GetString("Phone3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of Chief of Province.
        /// </summary>
        public static string pppc3 {
            get {
                return ResourceManager.GetString("pppc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Links.
        /// </summary>
        public static string PradeshKaryalaya {
            get {
                return ResourceManager.GetString("PradeshKaryalaya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Public Service Commission.
        /// </summary>
        public static string PradeshLokSewa {
            get {
                return ResourceManager.GetString("PradeshLokSewa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Policy &amp; Planning Commission.
        /// </summary>
        public static string PradeshNiti {
            get {
                return ResourceManager.GetString("PradeshNiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Assembly.
        /// </summary>
        public static string PradeshShabha {
            get {
                return ResourceManager.GetString("PradeshShabha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of the President of Nepal.
        /// </summary>
        public static string President {
            get {
                return ResourceManager.GetString("President", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Notice.
        /// </summary>
        public static string PressNotice {
            get {
                return ResourceManager.GetString("PressNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Release.
        /// </summary>
        public static string PressRelease {
            get {
                return ResourceManager.GetString("PressRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office of Prime Ministry.
        /// </summary>
        public static string PrimeMinister {
            get {
                return ResourceManager.GetString("PrimeMinister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Links.
        /// </summary>
        public static string provimplink {
            get {
                return ResourceManager.GetString("provimplink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Service Commission.
        /// </summary>
        public static string PSC {
            get {
                return ResourceManager.GetString("PSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Province 1.
        /// </summary>
        public static string psc1 {
            get {
                return ResourceManager.GetString("psc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Province 2.
        /// </summary>
        public static string psc2 {
            get {
                return ResourceManager.GetString("psc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gandaki Province.
        /// </summary>
        public static string psc4 {
            get {
                return ResourceManager.GetString("psc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Province 5.
        /// </summary>
        public static string psc5 {
            get {
                return ResourceManager.GetString("psc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Province 6.
        /// </summary>
        public static string psc6 {
            get {
                return ResourceManager.GetString("psc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Province 7.
        /// </summary>
        public static string psc7 {
            get {
                return ResourceManager.GetString("psc7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSC Content.
        /// </summary>
        public static string psccontent {
            get {
                return ResourceManager.GetString("psccontent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Gandaki Province.
        /// </summary>
        public static string pscGandaki {
            get {
                return ResourceManager.GetString("pscGandaki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Karnali Province.
        /// </summary>
        public static string pscKarnali {
            get {
                return ResourceManager.GetString("pscKarnali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Far Western Province.
        /// </summary>
        public static string pscSudur {
            get {
                return ResourceManager.GetString("pscSudur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publications.
        /// </summary>
        public static string Publication {
            get {
                return ResourceManager.GetString("Publication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action taken for irregularities in the examination.
        /// </summary>
        public static string Punishment {
            get {
                return ResourceManager.GetString("Punishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string RecentUpdates {
            get {
                return ResourceManager.GetString("RecentUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendation.
        /// </summary>
        public static string Recommend {
            get {
                return ResourceManager.GetString("Recommend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruitment.
        /// </summary>
        public static string recruitment {
            get {
                return ResourceManager.GetString("recruitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string Reserved {
            get {
                return ResourceManager.GetString("Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Act/Rules.
        /// </summary>
        public static string ResourcesDoc {
            get {
                return ResourceManager.GetString("ResourcesDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Social Development.
        /// </summary>
        public static string Samajik {
            get {
                return ResourceManager.GetString("Samajik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Links.
        /// </summary>
        public static string shortLink {
            get {
                return ResourceManager.GetString("shortLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province Policy and Planning Commission.
        /// </summary>
        public static string sppc {
            get {
                return ResourceManager.GetString("sppc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Menu.
        /// </summary>
        public static string SubMenu {
            get {
                return ResourceManager.GetString("SubMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Trade Tourism Forest Environment.
        /// </summary>
        public static string Udhyog {
            get {
                return ResourceManager.GetString("Udhyog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Visitor.
        /// </summary>
        public static string Visitor {
            get {
                return ResourceManager.GetString("Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written Exam.
        /// </summary>
        public static string WrittenExam {
            get {
                return ResourceManager.GetString("WrittenExam", resourceCulture);
            }
        }
    }
}
